name = "TFC a New Age"
author = "Just Enough Mail"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fc25d1977a8549a5d6d4ca13ef4bbe3dc8360eba009f62dc0569349ddb6d9e0"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
