name = "possible-tfc-pack"
author = "Just Enough Mail"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8bd895f1fa4ce841934f12a20e9b9e321566c9a2802aa6524f0acdba324b29b"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
