name = "possible-tfc-pack"
author = "Just Enough Mail"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18cf7e1939a7f19b92e661f54dfde1ca9af94c17919e92a2da79e5db777d6a93"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
