name = "Possible TFC Pack"
author = "NotEnoughMail"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f9237c0801ba11dee8b6f9065b5496e22eac1ad582238ee4e562c94aa2932b0"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
