name = "possible-tfc-pack"
author = "Just Enough Mail"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c34564ed87f6e28e8aebf844ed382698da2e73f5676ea5b434b61d1dfc672735"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
