name = "Possible TFC Pack"
author = "NotEnoughMail"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa34bedf39ec32ec72b33fae73226228ac2c5ab70c00dc5802e9a0fba7b2343c"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
