name = "TFC a New Age"
author = "Just Enough Mail"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f35cf9ed08e1c29a28df252e0be706d00fe25390538fe144d34394dd96daf8e"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
