name = "possible-tfc-pack"
author = "Just Enough Mail"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "137b09424b8503e87464ac0f03d84f1a81c5ce4b337043c95efd3e133dfca70c"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"
