name = "Possible TFC Pack"
author = "NotEnoughMail"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91c4eb18c5d4c406526919e65eb543c503a7212c051e7640b8610808229768d3"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
