onEvent('recipes', e => {
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:transpride"}'), ['2x #forge:dyes/light_blue', '2x #forge:dyes/pink', '#forge:dyes/white']).id('kubejs:crafting/shader/trans_pride');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:enbypride"}'), ['#forge:dyes/yellow', '#forge:dyes/white', '#forge:dyes/purple', '#forge:dyes/black']).id('kubejs:crafting/shader/enby_pride');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:gaypride"}'), ['#forge:dyes/green', '#forge:dyes/lime', '#forge:dyes/white', '#forge:dyes/light_blue', '#forge:dyes/purple']).id('kubejs:crafting/shader/gay_pride');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:lesbianpride"}'), ['#forge:dyes/red', '#forge:dyes/orange', '#forge:dyes/white', '#forge:dyes/magenta', '#forge:dyes/purple']).id('kubejs:crafting/shader/lesbian_pride');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:bipride"}'), ['2x #forge:dyes/pink', '#forge:dyes/purple', '2x #forge:dyes/blue']).id('kubejs:crafting/shader/bi_pride');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:acepride"}'), ['#forge:dyes/black', '#forge:dyes/gray', '#forge:dyes/white', '#forge:dyes/purple']).id('kubejs:crafting/shader/ace_pride'); // Pride of place
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:rosequartz"}'), ['2x #forge:dyes/pink', '#forge:dyes/brown']).id('kubejs:crafting/shader/rosequartz');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:argo"}'), ['#forge:dyes/orange', '#forge:dyes/light_gray', '#forge:dyes/black']).id('kubejs:crafting/shader/argo');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:sunstrike"}'), ['#forge:dyes/red', '2x #forge:dyes/orange', '#forge:dyes/gray']).id('kubejs:crafting/shader/sunstrike');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:locus"}'), ['#forge:dyes/green', '2x #forge:dyes/gray', '#forge:dyes/black']).id('kubejs:crafting/shader/locus');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:felix"}'), ['#forge:dyes/orange', '2x #forge:dyes/gray', '#forge:dyes/black']).id('kubejs:crafting/shader/felix');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:sharkface"}'), ['#forge:dyes/red', '2x #forge:dyes/gray', '#forge:dyes/black']).id('kubejs:crafting/shader/sharkface');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:dragonsbreath"}'), ['2x #forge:dyes/green', '#forge:dyes/light_gray', '#forge:dyes/black']).id('kubejs:crafting/shader/dragons_breath');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:hawk"}'), ['#forge:dyes/white', '#forge:dyes/black', '#forge:dyes/gray']).id('kubejs:crafting/shader/hawk');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:eyas"}'), ['#forge:dyes/red', '#forge:dyes/black', '#forge:dyes/gray']).id('kubejs:crafting/shader/eyas')
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:magnum"}'), ['2x #forge:dyes/light_gray', '#forge:dyes/brown']).id('kubejs:crafting/shader/magnum');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:fox"}'), ['#forge:dyes/white', '#forge:dyes/orange', '#forge:dyes/black']).id('kubejs:crafting.shader/fox');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:vaulttec"}'), ['2x #forge:dyes/blue', '#forge:dyes/yellow', '#forge:dyes/brown']).id('kubejs:crafting/shader/vault_tec');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:sponsor"}'), ['#forge:dyes/white', '2x #forge:dyes/red', '#forge:dyes/black']).id('kubejs:crafting.shader/sponsor');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:massfusion"}'), ['#forge:dyes/green', '#forge:dyes/gray', '#forge:dyes/yellow']).id('kubejs:crafting/shader/mass_fusion');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:stormflower"}'), ['2x #forge:dyes/green', '#forge:dyes/black']).id('kubejs:crafting/shader/stormflower');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:milo"}'), ['#forge:dyes/orange', '#forge:dyes/red', '#forge:dyes/black']).id('kubejs:crafting/shader/milo');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:trident"}'), ['#forge:dyes/cyan', '#forge:dyes/light_gray', '#forge:dyes/gray']).id('kubejs:crafting/shader/trident');
	e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:chloris"}'), ['#forge:dyes/lime', '2x #forge:dyes/black']).id('kubejs:crafting/shader/chloris');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:crescentrose"}'), ['2x #forge:dyes/red', '#forge:dyes/black']).id('kubejs:crafting/shader/cresent_rose');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:qrow"}'), ['#forge:dyes/black', '2x #forge:dyes/light_gray', '#forge:dyes/red']).id('kubejs:crafting/shader/qrow');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:lususnaturae"}'), ['#forge:dyes/light_gray', '2x #forge:dyes/black']).id('kubejs:crafting/shader/lusus_naturae');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:vanguard"}'), ['#forge:dyes/blue', '#forge:dyes/orange', '#forge:dyes/gray']).id('kubejs:crafting/shader/vanguard'); // https://www.youtube.com/playlist?list=PLTlpO3Ief-8F6VghbnWkylfcB5WQ1rBaM
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:regal"}'), ['#forge:dyes/white', '#forge:dyes/brown', '#forge:dyes/light_gray']).id('kubejs:crafting/shader/regal');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:harrowed"}'), ['2x #forge:dyes/brown', '#forge:dyes/black']).id('kubejs:crafting/shaped/harrowed');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:taken"}'), ['2x #forge:dyes/light_gray', '#forge:dyes/black']).id('kubejs:crafting/shader/taken');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:ikelos"}'), ['#forge:dyes/gray', '#forge:dyes/black', '#forge:dyes/orange', '#forge:dyes/brown']).id('kubejs:crafting.shader/ikelos');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:angelsthesis"}'), ['#forge:dyes/lime', '#forge:dyes/purple', '#forge:dyes/black']).id('kubejs:crafting/shader/angels_thesis');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:sutherland"}'), ['#forge:dyes/red', '#forge:dyes/purple', '#forge:dyes/black']).id('kubejs:crafting/shader/sutherland');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:exia"}'), ['#forge:dyes/light_gray', '#forge:dyes/blue', '#forge:dyes/yellow', '#forge:dyes/red']).id('kubejs:crafting/shader/exia');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:crimsonlotus"}'), ['#forge:dyes/red', '#forge:dyes/yellow', '#forge:dyes/black']).id('kubejs:crafting/shader/crimson_lotus');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:dominator"}'), ['#forge:dyes/cyan', '#forge:dyes/black', '#forge:dyes/brown']).id('kubejs:crafting/shader/dominator');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:warbird"}'), ['#forge:dyes/yellow', '2x #forge:dyes/light_gray', '#forge:dyes/black']).id('kubejs:crafting/shader/warbird');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:matrix"}'), ['#forge:dyes/lime', '#forge:dyes/light_gray', '#forge:dyes/green']).id('kubejs:crafting/shader/matrix');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:twili"}'), ['#forge:dyes/lime', '2x #forge:dyes/black', '#forge:dyes/gray']).id('kubejs:crafting/shader/twili');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:usurper"}'), ['#forge:dyes/gray', '#forge:dyes/red', '#forge:dyes/black', '#forge:dyes/brown']).id('kubejs:crafting/shader/usurper');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:ancient"}'), ['#forge:dyes/gray', '#forge:dyes/brown', '#forge:dyes/red']).id('kubejs:crafting/shader/ancient')
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:glacis"}'), ['2x #forge:glass/light_blue', '#forge:dyes/cyan']).id('kubejs:crafting/shader/glacis'); // This one is see through WTF IE
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:phoenix"}'), ['2x #forge:dyes/orange', '#forge:dyes/red']).id('kubejs:crafting/shader/phoenix');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:radiant"}'), ['#forge:dyes/light_gray', '#forge:dyes/yellow', '#forge:dyes/magenta', '#forge:dyes/purple']).id('kubejs:crafting/shader/radiant');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:hollow"}'), ['#forge:dyes/magenta', '#forge:dyes/yellow', '#forge:dyes/brown']).id('kubejs:crafting/shader/hollow');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:microshark"}'), ['#forge:dyes/pink', '#forge:dyes/light_gray', '#forge:dyes/magenta']).id('kubejs:crafting/shader/microshark'); // There are no good colors for this
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:n7"}'), ['#forge:dyes/white', '#forge:dyes/red', '#forge:dyes/gray', '#forge:dyes/black']).id('kubejs:crafting/shader/n7');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:normandy"}'), ['#forge:dyes/white', '#forge:dyes/black', '#forge:dyes/light_gray']).id('kubejs:crafting/shapeless/normandy');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:omnitool"}'), ['3x #forge:glass/orange', '#forge:dyes/black']).id('kubejs:crafting/shader/omnitool'); // This is also see through, again WTF IE
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:kindled"}'), ['#forge:dyes/orange', '#forge:dyes/gray', '#forge:dyes/black']).id('kubejs:crafting/shader/the_kindled');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:darkfire"}'), ['#forge:dyes/red', '#forge:dyes/blue', '#forge:dyes/black']).id('kubejs:crafting/shader/darkfire');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:erruption"}'), ['#forge:dyes/red', '#forge:dyes/orange', '#forge:dyes/brown', '#forge:dyes/black']).id('kubejs:crafting/shader/erruption');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:waaagh"}'), ['#forge:dyes/yellow', '#forge:dyes/orange', '#forge:dyes/black']).id('kubejs:crafting.shader/waaagh');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:astartes"}'), ['2x #forge:dyes/red', '#forge:dyes/light_gray', '#forge:dyes/black']);
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersiveengineering:netherforged"}'), ['#tfc:magma_blocks', '#forge:dyes/green', '#forge:dyes/gray']).id('kubejs:crafting/shader/netherforged');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersivepetroleum:blue"}'), ['#forge:glass_panes/colorless', '#forge:dyes/blue', '#forge:dyes/white', '#forge:dyes/gray']).id('kubejs:crafting/shader/blue_ashpd'); // Don't get the blue gell on yourself
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersivepetroleum:orange"}'), ['#forge:glass_panes/colorless', '#forge:dyes/orange', '#forge:dyes/white', '#forge:dyes/gray']).id('kubejs:crafting/shader/orange_ashpd');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersivepetroleum:cube0"}'), ['#forge:glass_panes/colorless', '#forge:dyes/cyan', '#forge:dyes/white', '#forge:dyes/gray']).id('kubejs:crafting/shader/storage_cube');
    e.shapeless(Item.of('immersiveengineering:shader', '{shader_name:"immersivepetroleum:cube1"}'), ['#forge:glass_panes/colorless', '#forge:dyes/pink', '#forge:dyes/white', '#forge:dyes/gray']).id('kubejs:crafting/shader/friend');
})