// priority: 0

console.info('Loading tag scripts')

onEvent('tags.blocks', e => {
	e.add('tfc:support_beam', 'create:metal_girder')
	e.add('create:passive_boiler_heaters', 'tfc:firepit')
	e.removeAllTagsFrom('create_crystal_clear:steel_glass_casing')
	e.removeAllTagsFrom('create_crystal_clear:steel_tinted_glass_casing')
});

let berries = ['cherry', 'wintergreen_berry', 'strawberry', 'snowberry', 'raspberry', 'gooseberry', 'elderberry', 'cranberry', 'cloudberry', 'bunchberry', 'blueberry', 'blackberry']

let tfc_metals = ['bismuth', 'bismuth_bronze', 'black_bronze', 'bronze', 'brass', 'copper', 'gold', 'nickel', 'rose_gold', 'silver', 'tin', 'zinc', 'sterling_silver', 'wrought_iron', 'cast_iron', 'steel', 'black_steel', 'blue_steel', 'red_steel']

onEvent('tags.items', e => {
	berries.forEach(berry => {
		e.add('tfc:foods/berries', 'tfc:food/' + berry)
	})
	tfc_metals.forEach(metal => {
		e.add('forge:rods/all_metal', 'tfc:metal/rod/' + metal)
	})
	e.add('create:sleepers', '#forge:smooth_stone_slab')
	e.add('tfc:rocks/loose', '#tfc:rock_knapping')
	e.add('tfc:kelp', 'tfc:plant/winged_kelp')
	e.add('tfc:kelp', 'tfc:plant/leafy_kelp')
	e.add('tfc:kelp', 'tfc:plant/giant_kelp_flower')
	//metal reorganization
	e.removeAllTagsFrom('immersiveengineering:plate_constantan')
	e.removeAllTagsFrom('immersiveengineering:nugget_constantan')
	e.removeAllTagsFrom('immersiveengineering:plate_electrum')
	e.removeAllTagsFrom('immersiveengineering:nugget_electrum')
	e.removeAllTagsFrom('immersiveengineering:plate_lead')
	e.removeAllTagsFrom('immersiveengineering:nugget_lead')
	e.add('forge:sheets', 'immersiveengineering:plate_constantan')
	e.add('forge:sheets', 'immersiveengineering:plate_electrum')
	e.add('forge:sheets', 'immersiveengineering:plate_lead')
	e.add('forge:sheets/constantan', 'immersiveengineering:plate_constantan')
	e.add('forge:sheets/electrum', 'immersiveengineering:plate_electrum')
	e.add('forge:sheets/lead', 'immersiveengineering:plate_lead')
	e.add('tfc:metal_item/constantan', 'immersiveengineering:plate_constantan')
	e.add('tfc:metal_item/constantan', 'immersiveengineering:ingot_constantan')
	e.add('tfc:metal_item/constantan', 'immersiveengineering:nugget_constantan')
	e.add('tfc:metal_item/constantan', 'immersiveengineering:stick_lead')
	e.add('tfc:metal_item/electrum', 'immersiveengineering:plate_electrum')
	e.add('tfc:metal_item/electrum', 'immersiveengineering:ingot_electrum')
	e.add('tfc:metal_item/electrum', 'immersiveengineering:nugget_electrum')
	e.add('tfc:metal_item/electrum', 'immersiveengineering:stick_lead')
	e.add('tfc:metal_item/lead', 'immersiveengineering:plate_lead')
	e.add('tfc:metal_item/lead', 'immersiveengineering:ingot_lead')
	e.add('tfc:metal_item/lead', 'immersiveengineering:nugget_lead')
	e.add('tfc:metal_item/lead', 'immersiveengineering:stick_lead')
	e.add('tfc:pileable_sheets', 'immersiveengineering:plate_constantan')
	e.add('tfc:pileable_sheets', 'immersiveengineering:plate_electrum')
	e.add('tfc:pileable_sheets', 'immersiveengineering:plate_lead')
	e.add('tfc:pileable_ingots', 'immersiveengineering:ingot_constantan')
	e.add('tfc:pileable_ingots', 'immersiveengineering:ingot_electrum')
	e.add('tfc:pileable_ingots', 'immersiveengineering:ingot_lead')
	e.add('forge:double_ingots', 'immersiveengineering:nugget_constantan')
	e.add('forge:double_ingots', 'immersiveengineering:nugget_electrum')
	e.add('forge:double_ingots', 'immersiveengineering:nugget_lead')
	e.add('forge:double_ingots/constantan', 'immersiveengineering:nugget_constantan')
	e.add('forge:double_ingots/electrum', 'immersiveengineering:nugget_electrum')
	e.add('forge:double_ingots/lead', 'immersiveengineering:nugget_lead')
	//tool rack, may turn into an array
	e.add('tfc:usable_on_tool_rack', 'create:wrench')
	e.add('tfc:usable_on_tool_rack', 'create:goggles')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:hammer')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:wirecutter')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:screwdriver')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:voltmeter')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:drill')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:buzzsaw')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:revolver')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:chemthrower')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:railgun')
	e.add('tfc:usable_on_tool_rack', 'immersiveengineering:skyhook')
	e.add('tfc:usable_on_tool_rack', 'gunswithoutroses:iron_gun')
	e.add('tfc:usable_on_tool_rack', 'gunswithoutroses:gold_gun')
	//weights, available weights => very_light, light, medium, heavy, very_heavy
	e.add('kubejs:utility/weight_medium', 'create:flywheel')
	e.add('kubejs:utility/weight_heavy', 'create:crushing_wheel')
	e.add('kubejs:utility/weight_light', 'immersiveengineering:glider')
	e.add('kubejs:utility/weight_medium', 'create:water_wheel')
	e.add('kubejs:utility/weight_heavy', 'create:schematicannon')
	e.add('kubejs:utility/weight_medium', 'create:fluid_tank')
	e.add('kubejs:utility/weight_heavy', 'create:steam_engine')
	e.add('kubejs:utility/weight_medium', 'create:item_vault')
	e.add('kubejs:utility/weight_heavy', 'create:mechanical_crafter')
	e.add('kubejs:utility/weight_medium', 'create:potato_cannon')
	e.add('kubjes:utility/weight_very_heavy', 'create:wand_of_symmetry')
	e.add('kubejs:utility/weight_light', 'create:wrench')
	e.add('kubejs:utility/weight_heavy', 'create:peculiar_bell')
	e.add('kubejs:utility/weight_medium', 'create:sturdy_sheet')
	e.add('kubejs:utility/weight_heavy', 'gunswithoutroses:iron_gun')
	e.add('kubejs:utility/weight_heavy', 'gunswithoutroses:gold_gun')
	e.add('kubejs:utility/weight_medium', 'chunkloader:basic_chunk_loader')
	e.add('kubejs:utility/weight_heavy', 'chunkloader:advanced_chunk_loader')
	e.add('kubejs:utility/weight_very_heavy', 'chunkloader:ultimate_chunk_loader')
	e.add('kubejs:utility/weight_medium', 'immersiveengineering:waterwheel_segment')
	e.add('kubejs:utility/weight_very_heavy', 'immersiveengineering:watermill')
	e.add('kubejs:utility/weight_medium', 'immersiveengineering:hammer')
	e.add('kubejs:utility/weight_light', 'immersiveengineering:wirecutter')
	e.add('kubejs:utility/weight_light', 'immersiveengineering:screwdriver')
	e.add('kubejs:utility/weight_light', 'toolbelt:pouch')
	e.add('kubejs:utility/weight_heavy', 'toolbelt:belt')
	//sizes, available sizes => tiny, very_small, small, normal, large, very_large, huge
	e.add('kubejs:utility/size_large', 'create:flywheel')
	e.add('kubejs:utility/size_large', 'create:crushing_wheel')
	e.add('kubejs:utility/size_normal', 'immersiveengineering:glider')
	e.add('kubejs:utility/size_normal', 'create:water_wheel')
	e.add('kubejs:utility/size_large', 'create:schematicannon')
	e.add('kubejs:utility/size_large', 'create:steam_engine')
	e.add('kubejs:utility/size_large', 'create:crafting_blueprint')
	e.add('kubejs:utility/size_huge', 'create:potato_cannon')
	e.add('kubejs:utility/size_huge', 'create:wand_of_symmetry')
	e.add('kubejs:utility/size_normal', 'create:wrench')
	e.add('kubejs:utility/size_small', 'create:goggles')
	e.add('kubejs:utility/size_large', 'create:sturdy_sheet')
	e.add('kubejs:utility/size_very_large', 'gunswithoutroses:iron_gun')
	e.add('kubejs:utility/size_very_large', 'gunswithoutroses:gold_gun')
	e.add('kubejs:utility/size_normal', 'chunkloader:basic_chunk_loader')
	e.add('kubejs:utility/size_large', 'chunkloader:advanced_chunk_loader')
	e.add('kubejs:utility/size_very_large', 'chunkloader:ultimate_chunk_loader')
	e.add('kubejs:utility/size_large', 'immersiveengineering:waterwheel_segment')
	e.add('kubejs:utility/size_huge', 'immersiveengineering:watermill')
	e.add('kubejs:utility/size_small', 'immersiveengineering:hammer')
	e.add('kubejs:utility/size_small', 'immersiveengineering:wirecutter')
	e.add('kubejs:utility/size_small', 'immersiveengineering:screwdriver')
	e.add('kubejs:utility/size_normal', 'toolbelt:pouch')
	e.add('kubejs:utility/size_very_large', 'toolbelt:belt')
})

onEvent('tags.fluids', e => {
	e.add('tfc:molten_metals', 'kubejs:electrum')
	e.add('tfc:molten_metals', 'kubejs:constantan')
	e.add('tfc:molten_metals', 'kubejs:lead')
	e.add('tfc:electrum', 'kubejs:electrum')
	e.add('tfc:electrum', 'kubejs:flowing_electrum')
	e.add('tfc:constantan', 'kubejs:constantan')
	e.add('tfc:constantan', 'kubejs:flowing_constantan')
	e.add('tfc:lead', 'kubejs:lead')
	e.add('tfc:lead', 'kubejs:flowing_lead')
	e.add('forge:true_water', 'minecraft:water')/*IE why do you require fluid tags for your inputs*/
	e.add('forge:true_water', 'minecraft:flowing_water')/*a normal fluid would be fine*/
	e.add('immersiveengineering:concrete', 'immersiveengineering:concrete')
	e.add('immersiveengineering:concrete', 'immersiveengineering:concrete_flowing')
})