let brick_colors = ['red', 'worn', 'dusk', 'scarlet', 'blue', 'pearl', 'dean']

let crack_or_not = ['', 'cracked_']

// You want moss?
onEvent('block.registry', e => {
    brick_colors.forEach(color => {
        // Not mossy
        crack_or_not.forEach(crack => {
            // Normal
            e.create('createdeco:' + crack + color + '_bricks', 'tfc:moss_growing_block')
                .mossyBlock('createdeco:mossy_' + color + '_bricks')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_brick_stair', 'tfc:moss_growing_stair')
                .mossyStair('createdeco:mossy_' + color + '_brick_stair')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_brick_slab', 'tfc:moss_growing_slab')
                .mossySlab('createdeco:mossy_' + color + '_brick_slab')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_brick_wall', 'tfc:moss_growing_wall')
                .mossyWall('createdeco:mossy_' + color + '_brick_wall')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            // Tiles
            e.create('createdeco:' + crack + color + '_brick_tiles', 'tfc:moss_growing_block')
                .mossyBlock('createdeco:mossy_' + color + '_brick_tiles')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_brick_tiles')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_brick_tiles_stair', 'tfc:moss_growing_stair')
                .mossyStair('createdeco:mossy_' + color + '_brick_tiles_stair')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_brick_tiles')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_brick_tiles_slab', 'tfc:moss_growing_slab')
                .mossySlab('createdeco:mossy_' + color + '_brick_tiles_slab')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_brick_tiles')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_brick_tiles_wall', 'tfc:moss_growing_wall')
                .mossyWall('createdeco:mossy_' + color + '_brick_tiles_wall')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_brick_tiles')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            // Long
            e.create('createdeco:' + crack + color + '_long_bricks', 'tfc:moss_growing_block')
                .mossyBlock('createdeco:mossy_' + color + '_long_bricks')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_long_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_long_brick_stair', 'tfc:moss_growing_stair')
                .mossyStair('createdeco:mossy_' + color + '_long_brick_stair')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_long_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_long_brick_slab', 'tfc:moss_growing_slab')
                .mossySlab('createdeco:mossy_' + color + '_long_brick_slab')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_long_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_long_brick_wall', 'tfc:moss_growing_wall')
                .mossyWall('createdeco:mossy_' + color + '_long_brick_wall')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_long_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            // Short
            e.create('createdeco:' + crack + color + '_short_bricks', 'tfc:moss_growing_block')
                .mossyBlock('createdeco:mossy_' + color + '_short_bricks')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_short_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_short_brick_stair', 'tfc:moss_growing_stair')
                .mossyStair('createdeco:mossy_' + color + '_short_brick_stair')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_short_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_short_brick_slab', 'tfc:moss_growing_slab')
                .mossySlab('createdeco:mossy_' + color + '_short_brick_slab')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_short_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
            e.create('createdeco:' + crack + color + '_short_brick_wall', 'tfc:moss_growing_wall')
                .mossyWall('createdeco:mossy_' + color + '_short_brick_wall')
                .textureAll('createdeco:block/palettes/bricks/' + color + '/' + crack + color + '_short_bricks')
                .material('stone')
                .requiresTool(true)
                .resistance(6)
                .hardness(1.5)
                .tagBlock('minecraft:mineable/pickaxe')
                .tagBlock('firmalife:oven_insulation')
                .tagBlock('tfc:bloomery_insulation')
        })
        // Mossy
        // Normal
        e.create('createdeco:mossy_' + color + '_bricks', 'tfc:moss_spreading_block')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_brick_stair', 'tfc:moss_spreading_stair')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_brick_slab', 'tfc:moss_spreading_slab')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_brick_wall', 'tfc:moss_spreading_wall')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        // Tiles
        e.create('createdeco:mossy_' + color + '_brick_tiles', 'tfc:moss_spreading_block')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_brick_tiles')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_brick_tiles_stair', 'tfc:moss_spreading_stair')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_brick_tiles')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_brick_tiles_slab', 'tfc:moss_spreading_slab')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_brick_tiles')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_brick_tiles_wall', 'tfc:moss_spreading_wall')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_brick_tiles')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        // Long
        e.create('createdeco:mossy_' + color + '_long_bricks', 'tfc:moss_spreading_block')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_long_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
         e.create('createdeco:mossy_' + color + '_long_brick_stair', 'tfc:moss_spreading_stair')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_long_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_long_brick_slab', 'tfc:moss_spreading_slab')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_long_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_long_brick_wall', 'tfc:moss_spreading_wall')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_long_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        // Short
        e.create('createdeco:mossy_' + color + '_short_bricks', 'tfc:moss_spreading_block')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_short_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
         e.create('createdeco:mossy_' + color + '_short_brick_stair', 'tfc:moss_spreading_stair')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_short_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_short_brick_slab', 'tfc:moss_spreading_slab')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_short_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
        e.create('createdeco:mossy_' + color + '_short_brick_wall', 'tfc:moss_spreading_wall')
            .textureAll('createdeco:block/palettes/bricks/' + color + '/mossy_' + color + '_short_bricks')
            .material('stone')
            .requiresTool(true)
            .resistance(6)
            .hardness(1.5)
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('firmalife:oven_insulation')
            .tagBlock('tfc:bloomery_insulation')
    })
})