// priority 10

const Integer = Java.loadClass('java.lang.Integer');
const Float = Java.loadClass('java.lang.Float');

global.oreGrades = ['normal', 'poor', 'rich'];

global.gradedOres = [];

global.ungradedOres = [];

global.allOres = [];
global.gradedOres.forEach(ore => {
    global.allOres.push(ore);
});
global.ungradedOres.forEach(ore => {
    global.allOres.push(ore);
});

global.metals = [{
    name: 'bismuth',
    mod: 'tfc',
    tools: false,
    sh: 0.02143,
    mt: 270,
    tier: 1
}, {
    name: 'bismuth_bronze',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 985,
    tier: 2
}, {
    name: 'black_bronze',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 1070,
    tier: 2
}, {
    name: 'bronze',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 950,
    tier: 2
}, {
    name: 'brass',
    mod: 'tfc',
    tools: false,
    sh: 0.00857,
    mt: 930,
    tier: 2
}, {
    name: 'copper',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 1080,
    tier: 1
}, {
    name: 'gold',
    mod: 'tfc',
    tools: false,
    sh: 0.005,
    mt: 1060,
    tier: 1
}, {
    name: 'nickel',
    mod: 'tfc',
    tools: false,
    sh: 0.00625,
    mt: 1453,
    tier: 1
}, {
    name: 'rose_gold',
    mod: 'tfc',
    tools: false,
    sh: 0.00857,
    mt: 960,
    tier: 1
}, {
    name: 'silver',
    mod: 'tfc',
    tools: false,
    sh: 0.00625,
    mt: 961,
    tier: 1
}, {
    name: 'tin',
    mod: 'tfc',
    tools: false,
    sh: 0.02143,
    mt: 230,
    tier: 1
}, {
    name: 'zinc',
    mod: 'tfc',
    tools: false,
    sh: 0.01429,
    mt: 420,
    tier: 1
}, {
    name: 'sterling_silver',
    mod: 'tfc',
    tools: false,
    sh: 0.00857,
    mt: 950,
    tier: 1
}, {
    name: 'wrought_iron',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 1535,
    tier: 3
}, {
    name: 'cast_iron',
    mod: 'tfc',
    tools: false,
    sh: 0.00857,
    mt: 1535,
    tier: 1
}, {
    name: 'steel',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 1540,
    tier: 4
}, {
    name: 'black_steel',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 1485,
    tier: 5
}, {
    name: 'blue_steel',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 1540,
    tier: 6
}, {
    name: 'red_steel',
    mod: 'tfc',
    tools: true,
    sh: 0.00857,
    mt: 1540,
    tier: 6
}, {
    name: 'chromium',
    mod: 'firmalife',
    tools: false,
    sh: 0.00696,
    mt: 1907,
    tier: 4
}, {
    name: 'stainless_steel',
    mod: 'firmalife',
    tools: false,
    sh: 0.00758,
    mt: 1540,
    tier: 4
}];

global.colors = ['black', 'red', 'green', 'brown', 'blue', 'purple', 'cyan', 'light_gray', 'gray', 'pink', 'lime', 'yellow', 'light_blue', 'magenta', 'orange', 'white'];

global.crops = [
    {
        name: 'barley',
        mod: 'tfc',
        minH: 18,
        maxH: 75,
        minT: -8,
        maxT: 26
    }, {
        name: 'beet',
        mod: 'tfc',
        minH: 18,
        maxH: 85,
        minT: -5,
        maxT: 20
    }, {
        name: 'cabbage',
        mod: 'tfc',
        minH: 15,
        maxH: 65,
        minT: -10,
        maxT: 27
    }, {
        name: 'carrot',
        mod: 'tfc',
        minH: 25,
        maxH: 100,
        minT: 3,
        maxT: 30
    }, {
        name: 'garlic',
        mod: 'tfc',
        minH: 15,
        maxH: 75,
        minT: -20,
        maxT: 18
    }, {
        name: 'green_bean',
        mod: 'tfc',
        minH: 38,
        maxH: 100,
        minT: 2,
        maxT: 25
    }, {
        name: 'jute',
        mod: 'tfc',
        minH: 25,
        maxH: 100,
        minT: 5,
        maxT: 37
    }, {
        name: 'maize',
        mod: 'tfc',
        minH: 75,
        maxH: 75,
        minT: 13,
        maxT: 40
    }, {
        name: 'melon',
        mod: 'tfc',
        minH: 75,
        maxH: 100,
        minT: 5,
        maxT: 37
    }, {
        name: 'oat',
        mod: 'tfc',
        minH: 35,
        maxH: 100,
        minT: 3,
        maxT: 40
    }, {
        name: 'onion',
        mod: 'tfc',
        minH: 15,
        maxH: 90,
        minT: 0,
        maxT: 30
    }, {
        name: 'papyrus',
        mod: 'tfc',
        minH: 70,
        maxH: 100,
        minT: 19,
        maxT: 37
    }, {
        name: 'potato',
        mod: 'tfc',
        minH: 50,
        maxH: 100,
        minT: -1,
        maxT: 37
    }, {
        name: 'pumpkin',
        mod: 'tfc',
        minH: 30,
        maxH: 80,
        minT: 0,
        maxT: 30
    }, {
        name: 'red_bell_pepper',
        mod: 'tfc',
        minH: 25,
        maxH: 60,
        minT: 16,
        maxT: 30
    }, {
        name: 'rice',
        mod: 'tfc',
        minH: 25,
        maxH: 100,
        minT: 15,
        maxT: 30
    }, {
        name: 'rye',
        mod: 'tfc',
        minH: 25,
        maxH: 85,
        minT: -11,
        maxT: 30
    }, {
        name: 'soybean',
        mod: 'tfc',
        minH: 40,
        maxH: 100,
        minT: 8,
        maxT: 30
    }, {
        name: 'squash',
        mod: 'tfc',
        minH: 23,
        maxH: 95,
        minT: 5,
        maxT: 33
    }, {
        name: 'sugarcane',
        mod: 'tfc',
        minH: 40,
        maxH: 100,
        minT: 12,
        maxT: 38
    }, {
        name: 'tomato',
        mod: 'tfc',
        minH: 30,
        maxH: 95,
        minT: 0,
        maxT: 36
    }, {
        name: 'wheat',
        mod: 'tfc',
        minH: 25,
        maxH: 100,
        minT: -4,
        maxT: 35
    }, {
        name: 'yellow_bell_pepper',
        mod: 'tfc',
        minH: 25,
        maxH: 60,
        minT: 16,
        maxT: 30
    }, { // Future update
        name: 'red_grape',
        mod: 'firmalife',
        minH: 0,
        maxH: 100,
        minT: 0,
        maxT: 50
    }, {
        name: 'white_grape',
        mod: 'firmalife',
        minH: 0,
        maxH: 100,
        minT: 0,
        maxT: 50
    }
];

global.plants = [
    {
        name: 'cocoa_sapling',
        mod: 'firmalife',
        minH: 16,
        maxH: 100,
        minT: 13,
        maxT: 42
    }, {
        name: 'fig_sapling',
        mod: 'firmalife',
        minH: 15,
        maxH: 100,
        minT: 13,
        maxT: 42
    }, {
        name: 'nightshade_bush',
        mod: 'firmalife',
        minH: 24,
        maxH: 100,
        minT: 7,
        maxT: 24
    }, {
        name: 'pineapple_bush',
        mod: 'firmalife',
        minH: 30,
        maxH: 100,
        minT: 20,
        maxT: 32
    }, {
        name: 'banana_sapling',
        mod: 'tfc',
        minH: 33,
        maxH: 100,
        minT: 10,
        maxT: 42
    }, {
        name: 'blackberry_bush',
        mod: 'tfc',
        minH: 24,
        maxH: 100,
        minT: 7,
        maxT: 24
    }, {
        name: 'blueberry_bush',
        mod: 'tfc',
        minH: 12,
        maxH: 100,
        minT: 7,
        maxT: 39
    }, {
        name: 'bunchberry_bush',
        mod: 'tfc',
        minH: 24,
        maxH: 100,
        minT: 15,
        maxT: 35
    }, {
        name: 'cherry_sapling',
        mod: 'tfc',
        minH: 12,
        maxH: 100,
        minT: -2,
        maxT: 32
    }, {
        name: 'cloudberry_bush',
        mod: 'tfc',
        minH: 9,
        maxH: 100,
        minT: -2,
        maxT: 17
    }, {
        name: 'cranberry_bush',
        mod: 'tfc',
        minH: 30,
        maxH: 100,
        minT: -5,
        maxT: 17
    }, {
        name: 'elderberry_bush',
        mod: 'tfc',
        minH: 12,
        maxH: 100,
        minT: 10,
        maxT: 33
    }, {
        name: 'gooseberry_bush',
        mod: 'tfc',
        minH: 24,
        maxH: 100,
        minT: 5,
        maxT: 27
    }, {
        name: 'green_apple_sapling',
        mod: 'tfc',
        minH: 13,
        maxH: 100,
        minT: -6,
        maxT: 32
    }, {
        name: 'lemon_sapling',
        mod: 'tfc',
        minH: 21,
        maxH: 100,
        minT: 3,
        maxT: 37
    }, {
        name: 'olive_sapling',
        mod: 'tfc',
        minH: 18,
        maxH: 100,
        minT: -2,
        maxT: 37
    }, {
        name: 'orange_sapling',
        mod: 'tfc',
        minH: 30,
        maxH: 100,
        minT: 8,
        maxT: 43
    }, {
        name: 'peach_sapling',
        mod: 'tfc',
        minH: 7,
        maxH: 100,
        minT: -3,
        maxT: 34
    }, {
        name: 'plum_sapling',
        mod: 'tfc',
        minH: 30,
        maxH: 100,
        minT: 8,
        maxT: 38
    }, {
        name: 'raspberry_bush',
        mod: 'tfc',
        minH: 24,
        maxH: 100,
        minT: 5,
        maxT: 25
    }, {
        name: 'red_apple_sapling',
        mod: 'tfc',
        minH: 12,
        maxH: 100,
        minT: -6,
        maxT: 32
    }, {
        name: 'snowberry_bush',
        mod: 'tfc',
        minH: 24,
        maxH: 100,
        minT: -7,
        maxT: 18
    }, {
        name: 'strawberry_bush',
        mod: 'tfc',
        minH: 12,
        maxH: 100,
        minT: 5,
        maxT: 28
    }, {
        name: 'wintergreen_berry_bush',
        mod: 'tfc',
        minH: 12,
        maxH: 100,
        minT: -6,
        maxT: 17
    }
];
