// priority: 0

console.info('Hiding precious items')

onEvent('jei.hide.items', e => {
	e.hide('gunswithoutroses:hunger_bullet')
	e.hide('gunswithoutroses:blaze_bullet')
	e.hide('gunswithoutroses:iron_bullet')
	e.hide('gunswithoutroses:diamond_gatling')
	e.hide('gunswithoutroses:diamond_sniper')
	e.hide('gunswithoutroses:diamond_shotgun')
	e.hide('immersiveengineering:pickaxe_steel')
	e.hide('immersiveengineering:shovel_steel')
	e.hide('immersiveengineering:axe_steel')
	e.hide('immersiveengineering:hoe_steel')
	e.hide('immersiveengineering:sword_steel')
	e.hide('createaddition:copper_wire')
	e.hide('createaddition:iron_wire')
	e.hide('createaddition:gold_wire')
	e.hide('createaddition:copper_spool')
	e.hide('createaddition:gold_spool')
	e.hide('minecraft:chest_minecart')
	e.hide('minecraft:enchanting_table')
	e.hide('%brewing')
	e.hide('%combat')
	e.hide('%tools')
	e.hide('%food')
	e.hide(/minecraft:.*_spawn_egg/)
	e.hide(/tfc:spawn_egg.*/)
	e.hide(/minecraft:.*candle/)
	e.hide('minecraft:elytra')
	e.hide('minecraft:oak_boats')
	e.hide('minecraft:spruce_boat')
	e.hide('minecraft:birch_boat')
	e.hide('minecraft:jungle_boat')
	e.hide('minecraft:acacia_boat')
	e.hide('minecraft:dark_oak_boat')
	e.hide('minecraft:furnace_minecart')
	e.hide('createaddition:redstone_relay')
	e.hide('createaddition:connector')
	e.hide(/createaddition:.*cake.*/)
	e.hide('createaddition:zinc_sheet')
	e.hide('createaddition:accumulator')
	e.hide(/createaddition:.*_rod/)
	e.hide('immersiveengineering:manual')
	e.hide(/immersiveengineering:armor_steel_.*/)
})

onEvent('jei.add.items', e => {
	e.add('minecraft:cauldron')
	e.add('minecraft:rabbit_foot')
	e.add('minecraft:fermented_spider_eye')
	e.add('minecraft:bow')
	e.add('minecraft:arrow')
	e.add('minecraft:crossbow')
	e.add(/tfc:.*shield.*/)
	e.add('minecraft:lead')
	e.add('minecraft:name_tag')
	e.add(Item.of('toolbelt:belt', '{Size:5}'))
	e.add('toolbelt:pouch')
	e.add('minecraft:flint_and_steel')
	e.add('minecraft:clock')
	e.add('minecraft:spyglass')
	e.add('minecraft:compass')
	e.add('minecraft:fishing_rod')
	e.add('minecraft:pumpkin_pie')
	e.add('minecraft:spider_eye')
	e.add('minecraft:rotten_flesh')
	e.add('minecraft:melon_slice')
})

onEvent('jei.remove.categories', e => {
	console.log(e.getCategoryIds())
	e.remove('minecraft:anvil')
	e.remove('minecraft:blasting')
	e.remove('minecraft:brewing')
	e.remove('minecraft:campfire')
	e.remove('minecraft:compostable')
	e.remove('minecraft:fuel')
	e.remove('minecraft:furnace')
	e.remove('minecraft:smithing')
	e.remove('minecraft:smoking')
	e.remove('create:automatic_brewing')
	e.remove('create:fan_haunting')
	e.remove('create:mystery_conversion')
	e.remove('immersiveengineering:arcfurnace_recycling')
	e.remove('cobblegenrandomizer:basalt_gen')
	e.remove('cobblegenrandomizer:cobble_gen')
	e.remove('cobblegenrandomizer:stone_gen')
	e.remove('jeresources:dungeon')
	e.remove('jeresources:enchantment')
	e.remove('jeresources:villager')
})