
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Cobble gen
		block_list_cobble = ["tfc:rock/hardened/rhyolite"]
		#Stone gen
		block_list_stone = ["tfc:rock/hardened/rhyolite"]
		#Basalt gen
		block_list_basalt = ["tfc:rock/hardened/basalt"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [["cobblestone", "tfc:rock/cobble/granite", ["tfc:rock/cobble/granite"]], ["cobblestone", "tfc:rock/cobble/diorite", ["tfc:rock/cobble/diorite"]], ["cobblestone", "tfc:rock/cobble/gabbro", ["tfc:rock/cobble/gabbro"]], ["cobblestone", "tfc:rock/cobble/shale", ["tfc:rock/cobble/shale"]], ["cobblestone", "tfc:rock/cobble/claystone", ["tfc:rock/cobble/claystone"]], ["cobblestone", "tfc:rock/cobble/limestone", ["tfc:rock/cobble/limestone"]], ["cobblestone", "tfc:rock/cobble/conglomerate", ["tfc:rock/cobble/conglomerate"]], ["cobblestone", "tfc:rock/cobble/dolomite", ["tfc:rock/cobble/dolomite"]], ["cobblestone", "tfc:rock/cobble/chert", ["tfc:rock/cobble/chert"]], ["cobblestone", "tfc:rock/cobble/chalk", ["tfc:rock/cobble/chalk"]], ["cobblestone", "tfc:rock/cobble/rhyolite", ["tfc:rock/cobble/rhyolite"]], ["cobblestone", "tfc:rock/cobble/basalt", ["tfc:rock/cobble/basalt"]], ["cobblestone", "tfc:rock/cobble/andesite", ["tfc:rock/cobble/andesite"]], ["cobblestone", "tfc:rock/cobble/dacite", ["tfc:rock/cobble/dacite"]], ["cobblestone", "tfc:rock/cobble/quartzite", ["tfc:rock/cobble/quartzite"]], ["cobblestone", "tfc:rock/cobble/slate", ["tfc:rock/cobble/slate"]], ["cobblestone", "tfc:rock/cobble/phyllite", ["tfc:rock/cobble/phyllite"]], ["cobblestone", "tfc:rock/cobble/schist", ["tfc:rock/cobble/schist"]], ["cobblestone", "tfc:rock/cobble/gneiss", ["tfc:rock/cobble/gneiss"]], ["cobblestone", "tfc:rock/cobble/marble", ["tfc:rock/cobble/marble"]]]

